doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:

            AccessControlBundle:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/vendor/ukickeru/access-control-bundle/config/packages/doctrine/mapping'
                prefix: 'ukickeru\AccessControlBundle\Model'
                alias: AccessControlBundle
