security:
    encoders:
        ukickeru\AccessControlBundle\Model\User:
            algorithm: auto

    providers:
        user_provider:
            id: ukickeru\AccessControlBundle\Application\Security\Authentication\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            lazy: false
            provider: user_provider
            guard:
                authenticators:
                    - ukickeru\AccessControlBundle\Application\Security\Authentication\AppAuthenticator
            logout:
                path: logout
                target: app_login
                invalidate_session: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_FULLY] }