security:
    encoders:
        ukickeru\AccessControlBundle\Application\Security\Authentication\UserAdapter:
            algorithm: auto

    providers:
        user_provider:
            id: ukickeru\AccessControlBundle\Application\Security\Authentication\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            lazy: false
            provider: user_provider
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 86400
                path:     /
            guard:
                authenticators:
                    - ukickeru\AccessControlBundle\Application\Security\Authentication\AppAuthenticator
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER] }