security:
    enable_authenticator_manager: true

    encoders:
        ukickeru\AccessControlBundle\Model\User:
            algorithm: auto

    providers:
        user_provider:
            id: ukickeru\AccessControlBundle\Application\Security\Authentication\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            json_login:
                provider: user_provider
                check_path: api_login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            lazy: false
            provider: user_provider
            guard:
                authenticators:
                    - ukickeru\AccessControlBundle\Application\Security\Authentication\AppAuthenticator
            logout:
                path: logout
                target: app_login
                invalidate_session: true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_FULLY] }
