ukickeru\AccessControlBundle\Model\Group:
  type: entity
  repositoryClass: ukickeru\AccessControlBundle\Infrastructure\Repository\Doctrine\GroupRepository
  table: "`group`"
  indexes:
    id_index:
      columns: [ id ]

  id:
    id:
      type: string
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: ukickeru\AccessControlBundle\Model\Service\IdGenerator

  fields:
    name:
      type: string
      length: 255
      unique: true
      nullable: false
    creationDate:
      type: date
      nullable: false
    availableRoutes:
      type: array
      nullable: true

  manyToOne:
    creator:
      targetEntity: ukickeru\AccessControlBundle\Model\User
      nullable: false
      joinColumn:
        name: creator
        referencedColumnName: id
        onDelete: CASCADE

    parentGroup:
      targetEntity: ukickeru\AccessControlBundle\Model\Group
      nullable: true
      joinColumn:
        name: parent_group_id
        referencedColumnName: id
        onDelete: SET NULL

  manyToMany:
    users:
      targetEntity: ukickeru\AccessControlBundle\Model\User
      cascade: ["persist", "merge"]
      fetch: EAGER
      mappedBy: groups

  lifecycleCallbacks:
    prePersist: [ setCreationDate ]
