ukickeru\AccessControlBundle\Model\User:
  type: entity
  repositoryClass: ukickeru\AccessControlBundle\Infrastructure\Repository\Doctrine\UserRepository
  table: "`user`"
  indexes:
    id_index:
      columns: [ id ]

  id:
    id:
      type: string
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: ukickeru\AccessControlBundle\Model\Service\IdGenerator

  fields:
    username:
      type: string
      length: 180
      unique: true
      nullable: false
    password:
      type: string
      nullable: false
    roles:
      type: array
    admin:
      type: boolean
      nullable: false
      options:
        default: false

  manyToMany:
    groups:
      targetEntity: ukickeru\AccessControlBundle\Model\Group
      cascade: ["persist", "merge"]
      fetch: EAGER
      inversedBy: users
      joinTable:
        name: users_groups
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          group_id:
            referencedColumnName: id
