parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ukickeru\AccessControl\:
        resource: '%kernel.project_dir%/vendor/ukickeru/access-control/src/'

    ukickeru\AccessControlBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    ukickeru\AccessControlBundle\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']
